name: Build USD Asset Resolvers against Houdini

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: "build"
  cancel-in-progress: false

jobs:

  build:
    runs-on: ubuntu-latest
    environment: houdini
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
          sudo apt-get install -y python3 python3-pip
          sudo pip3 install requests
      - name: Install Houdini
        env:
          SIDEFX_CLIENT_ID: '${{ secrets.SIDEFX_CLIENT_ID }}'
          SIDEFX_CLIENT_SECRET_KEY: '${{ secrets.SIDEFX_CLIENT_SECRET_KEY }}'
        run: |
          sudo --preserve-env python3 .github/workflows/build_houdini.py --houdini_install
      - name: Build USD File Resolver
        run: |
          pushd /opt/hfs > /dev/null && source houdini_setup && popd > /dev/null
          export RESOLVER_NAME=fileResolver
          cmake . -B build && cmake --build build --clean-first
          cmake --install build   
      - name: Build USD Python Resolver
        run: |
          pushd /opt/hfs > /dev/null && source houdini_setup && popd > /dev/null
          export RESOLVER_NAME=pythonResolver
          cmake . -B build && cmake --build build --clean-first              # make clean all
          cmake --install build
      - name: Print Result
        run: |
            echo dist/*