name: Build USD Asset Resolvers against Houdini

on:
  release:
    types: [released]
  schedule:
      - cron: '0 12 * * *'
  workflow_dispatch:

concurrency:
  group: "build"
  cancel-in-progress: false

jobs:

  build_windows:
    runs-on: windows-2019
    environment: houdini
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Switch to latest release tag
        run: |
          git fetch --all --tags
          latest_release_tag=$(git tag -l --sort=-version:refname  v* | head -1)
          git checkout tags/$latest_release_tag
      - name: Install system packages
        run: |
          pip3 install requests
      - name: Install Houdini
        env:
          SIDEFX_CLIENT_ID: '${{ secrets.SIDEFX_CLIENT_ID }}'
          SIDEFX_CLIENT_SECRET_KEY: '${{ secrets.SIDEFX_CLIENT_SECRET_KEY }}'
        run: |
          python3 .github/scripts/houdini.py --install